In [3]:
import pandas as pd
from datasets import load_dataset

df = load_dataset("ronantakizawa/leetcode-assembly", split="train").to_pandas()

# Filter to one target toolchain for v1 and remove uneeded columns
df = df[df["architecture"] == "aarch64"]
df = df[df["compiler"] == "ARM64 gcc 15.2.0"]
df = df[[
    "problem_id",
    "problem_title",
    "difficulty",
    "c_source",
    "optimization",
    "assembly",
    
]].copy()


wide = (
    df.pivot_table(
        index=["problem_id", "problem_title", "difficulty", "c_source"],
        columns="optimization",
        values="assembly",
        aggfunc="first",
    )
    .rename(columns={"-O0": "assembly_00", "-O1": "assembly_01", "-O2": "assembly_02", "-O3": "assembly_03"})
    .reset_index()
)
wide.columns.name = None


wide

/Users/shreybirmiwal/projects/gen-optimize-assembly/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

,problem_id,problem_title,difficulty,c_source,assembly_00,assembly_01,assembly_02,assembly_03
0,1,Two Sum,Easy,"/*\n1. Two Sum\n\nGiven an array of integers, ...","cmp:\n sub sp, sp, #16\n str...","cmp:\n ldr w2, [x0]\n ldr ...","cmp:\n ldr w2, [x0]\n ldr ...","cmp:\n ldr w2, [x0]\n ldr ..."
1,2,Add Two Numbers,Medium,/*\n2. Add Two Numbers\n\nYou are given two no...,"addTwoNumbers:\n stp x29, x30, [sp,...","addTwoNumbers:\n stp x29, x30, [sp,...","addTwoNumbers:\n stp x29, x30, [sp,...","addTwoNumbers:\n stp x29, x30, [sp,..."
2,3,Longest Substring Without Repeating Characters,Medium,/*\n3. Longest Substring Without Repeating Cha...,"lengthOfLongestSubstring:\n sub sp,...","lengthOfLongestSubstring:\n sub sp,...","lengthOfLongestSubstring:\n sub sp,...","lengthOfLongestSubstring:\n sub sp,..."
3,4,Median of Two Sorted Arrays,Hard,/*\n4. Median of Two Sorted Arrays\n\nThere ar...,"bs:\n sub sp, sp, #32\n str ...","bs:\n mov x5, x0\n subs w...","bs:\n subs w1, w1, #1\n bmi ...","bs:\n subs w1, w1, #1\n bmi ..."
4,5,Longest Palindromic Substring,Medium,/*\n5. Longest Palindromic Substring\n\nGiven ...,"longestPalindrome:\n stp x29, x30, ...","longestPalindrome:\n stp x29, x30, ...","longestPalindrome:\n cbz x0, .L11\n...","longestPalindrome:\n cbz x0, .L26\n..."
...,...,...,...,...,...,...,...,...
436,1007,Minimum Domino Rotations For Equal Row,Medium,/*\n1007. Minimum Domino Rotations For Equal R...,"minDominoRotations:\n sub sp, sp, #...","minDominoRotations:\n cmp w1, 0\n ...","minDominoRotations:\n cmp w1, 0\n ...","minDominoRotations:\n cmp w1, 0\n ..."
437,1008,Construct Binary Search Tree from Preorder Tra...,Medium,/*\n1008. Construct Binary Search Tree from Pr...,"bstFromPreorder:\n stp x29, x30, [s...","bstFromPreorder:\n stp x29, x30, [s...","bstFromPreorder:\n stp x29, x30, [s...","bstFromPreorder:\n stp x29, x30, [s..."
438,1011,Capacity To Ship Packages Within D Days,Medium,/*\n1011. Capacity To Ship Packages Within D D...,"count_days:\n sub sp, sp, #32\n ...","count_days:\n cmp w1, 0\n bl...","count_days:\n cmp w1, 0\n bl...","count_days:\n cmp w1, 0\n bl..."
439,1143,Longest Common Subsequence,Medium,#include <stdio.h>\n#include <stdlib.h>\n#incl...,"max:\n sub sp, sp, #16\n str...",longestCommonSubsequence:\n stp x29...,longestCommonSubsequence:\n stp x29...,longestCommonSubsequence:\n stp x29...
440,1312,Minimum Insertion Steps to Make a String Palin...,Hard,#include <stdio.h>\n#include <stdlib.h>\n#incl...,"min:\n sub sp, sp, #16\n str...","minInsertions:\n stp x29, x30, [sp,...","minInsertions:\n stp x29, x30, [sp,...","minInsertions:\n stp x29, x30, [sp,..."

In [4]:
# can we see the row 1 in more detail each column (not cutoff the text)
pd.set_option('display.max_colwidth', None)
wide.iloc[0]

# can i see this in a text file
wide.iloc[0].to_csv("wide.txt", index=False)

In [4]:
import pandas as pd
df2 = pd.read_csv("/Users/shreybirmiwal/projects/gen-optimize-assembly/src/codeforces-approach/data/codeforces_join.csv")
df2.sample(2)

,contest_id,index,official_tests,accepted_cpp_solution,assembly_compiler_image,assembly_compiler_platform,assembly_compiler_version,assembly_compiler_target,assembly_container_uname,assembly_command_o0,assembly_command_o3,assembly_o0,assembly_o3,assembly_compile_ok,assembly_compile_error,dataset_split
2521,1098,D,"[{'input': '2\r\n+ 1\r\n- 1\r\n', 'output': '0...",#include <bits/stdc++.h>\n#define fi first\n#d...,gcc:13,linux/arm64,g++ (GCC) 13.4.0,aarch64-linux-gnu,Linux 7e81b3d9ee07 6.10.14-linuxkit #1 SMP Thu...,g++ -std=gnu++17 -O0 -S submission.cpp -o subm...,g++ -std=gnu++17 -O3 -S submission.cpp -o subm...,"\t.arch armv8-a\n\t.file\t""submission.cpp""\n\t...","\t.arch armv8-a\n\t.file\t""submission.cpp""\n\t...",True,NaN,SFT
5788,1914,F,[{'input': '6\r\n4\r\n1 2 1\r\n2\r\n1\r\n5\r\n...,#include <iostream>\n#include <algorithm>\n#in...,gcc:13,linux/arm64,g++ (GCC) 13.4.0,aarch64-linux-gnu,Linux 7e81b3d9ee07 6.10.14-linuxkit #1 SMP Thu...,g++ -std=gnu++17 -O0 -S submission.cpp -o subm...,g++ -std=gnu++17 -O3 -S submission.cpp -o subm...,"\t.arch armv8-a\n\t.file\t""submission.cpp""\n\t...","\t.arch armv8-a\n\t.file\t""submission.cpp""\n\t...",True,NaN,SFT